---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(slingshot)
pal <- c(RColorBrewer::brewer.pal(9, "Set1"), RColorBrewer::brewer.pal(8, "Set2"))
# Save the objects as separate matrices for input in slingshot
dimred <- combined@reductions$umap@cell.embeddings
clustering <- combined$integrated_snn_res.0.5
counts <- as.matrix(combined@assays$RNA@counts[combined@assays$RNA@var.features, ])
set.seed(1)
jpeg('./reclustering/pseudotime/nodes.jpg', height=800, width=1500)
lineages <- getLineages(data = dimred, clusterLabels = clustering)
par(mfrow = c(1, 2))
plot(dimred[, 1:2], col = pal[clustering], cex = 0.5, pch = 16)
for (i in levels(clustering)) {
    text(mean(dimred[clustering == i, 1]), mean(dimred[clustering == i, 2]), labels = i, font = 2)
}

plot(dimred[, 1:2], col = pal[clustering], cex = 0.5, pch = 16)
lines(lineages, lwd = 3, col = "black")
dev.off()
jpeg('./reclustering/pseudotime/unsupervised_lineages.jpg',height=800,width=1500)
curves <- getCurves(lineages, approx_points = 300, thresh = 0.01, stretch = 0.8, allow.breaks = FALSE, shrink = 0.99)
plot(dimred, col = pal[clustering], asp = 1, pch = 16)
lines(curves, lwd = 3, col = "black")
dev.off()
```
